### ISSUE TITLE
TypeError: Cannot set property SitemapItemStream of #<Object> which has only a getter

### ISSUE THREAD

**Issue by egeres** [kamranahmedse/developer-roadmap#4469]
### What is the URL where the issue is happening

None

### Describe the Bug

I just cloned the repo and ran `npm install && npm run dev` but I get the attached error below, I can't find information about this error on the repository

### Output from browser console (if any)

λ npm run dev

> roadmap.sh@0.0.1 dev
> astro dev --port 3000

C:\Github\developer-roadmap\node_modules\sitemap\dist\index.js:13
exports.simpleSitemapAndIndex = exports.IndexObjectStreamToJSON = exports.XMLToSitemapIndexStream = exports.parseSitemapIndex = exports.ObjectStreamToJSON = exports.XMLToSitemapItemStream = exports.parseSitemap = exports.xmlLint = exports.ReadlineStream = exports.normalizeURL = exports.validateSMIOptions = exports.mergeStreams = exports.lineSeparatedURLsToSitemapOptions = exports.SitemapStream = exports.streamToPromise = exports.SitemapAndIndexStream = exports.SitemapIndexStream = exports.IndexTagNames = exports.SitemapItemStream = void 0;
^

TypeError: Cannot set property SitemapItemStream of #<Object> which has only a getter
    at Object.<anonymous> (C:\Github\developer-roadmap\node_modules\sitemap\dist\index.js:13:537)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Github\developer-roadmap\node_modules\sitemap\dist\lib\sitemap-simple.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.6.0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ausgomez** [comment]
this seems to be an issue with node 20.6.0 (current), can you try running it with LTS (18.17.1) ?
